version: '3.9'
services:
  db:
    image: postgres:13
    container_name: local_postgres
    restart: always
    volumes:
      - ./volume/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: inventory_mgmt
    ports:
      - "5432:5432"

  app:
    build: .
    container_name: app_server
    depends_on:
      - db
    ports:
      - "4001:4001"
    links:
      - db
    environment:
      GOOGLE_SHEET_ID: ${GOOGLE_SHEET_ID}
      GOOGLE_API_KEY: ${GOOGLE_API_KEY}
      LOCATION_ID: ${LOCATION_ID}


  # PostgreSQL pgAdmin panel accessible at http://localhost:5050/
  pgadmin-compose:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: user@nory.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 5050
    ports:
      - "5050:5050"
    depends_on:
      - db